<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Timesheet</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .info-box {
            margin-bottom: 20px;
            padding: 15px;
            background-color: #f5f5f5;
            border: 1px solid #ddd;
        }
        .info-row {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #4CAF50;
            color: white;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .total-row {
            background-color: #e8f5e9 !important;
            font-weight: bold;
        }
        .status-pending { color: #ff9800; }
        .status-approved { color: #4caf50; }
        .status-rejected { color: #f44336; }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Employee Timesheet</h1>
        <p>{{ $employeeName }}</p>
        <p>Period: {{ \Carbon\Carbon::parse($startDate)->format('M d, Y') }} - {{ \Carbon\Carbon::parse($endDate)->format('M d, Y') }}</p>
    </div>

    <div class="info-box">
        <div class="info-row"><strong>Total Hours Worked:</strong> {{ number_format($totalHours, 2) }} hours</div>
        <div class="info-row"><strong>Total Entries:</strong> {{ count($entries) }}</div>
        <div class="info-row"><strong>Generated:</strong> {{ now()->format('M d, Y H:i') }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Clock In</th>
                <th>Clock Out</th>
                <th>Break (min)</th>
                <th>Total Hours</th>
                <th>Status</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
            @foreach($entries as $entry)
            <tr>
                <td>{{ $entry->clock_in->format('M d, Y') }}</td>
                <td>{{ $entry->clock_in->format('h:i A') }}</td>
                <td>{{ $entry->clock_out ? $entry->clock_out->format('h:i A') : 'N/A' }}</td>
                <td>{{ $entry->break_minutes }}</td>
                <td>{{ number_format($entry->total_hours ?? 0, 2) }}</td>
                <td class="status-{{ $entry->status }}">{{ ucfirst($entry->status) }}</td>
                <td>{{ $entry->notes ?? '' }}</td>
            </tr>
            @endforeach
            <tr class="total-row">
                <td colspan="4" style="text-align: right;">TOTAL:</td>
                <td>{{ number_format($totalHours, 2) }}</td>
                <td colspan="2"></td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        <p>This is a system-generated timesheet. For payroll purposes only.</p>
        <p>Generated by yachtCRM Timeclock Module</p>
    </div>
</body>
</html>

